### ISSUE TITLE
System crashes when no fastq_paths found during summing fastq file sizes

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/auto-illumina-run-qc-check#12]
We've experienced an error where the list of `fastq_paths` is empty while summing the sizes of all fastq files on a run:

```
Traceback (most recent call last):
  File "auto-illumina-run-qc-check", line 33, in <module>
    sys.exit(load_entry_point('auto-illumina-run-qc-check', 'console_scripts', 'auto-illumina-run-qc-check')())
  File "auto_illumina_run_qc_check/__main__.py", line 66, in main
    core.qc_check(config, run)
  File "auto_illumina_run_qc_check/core.py", line 168, in qc_check
    sum_sample_fastq_file_sizes = get_sum_sample_fastq_file_sizes(run)
  File "auto_illumina_run_qc_check/core.py", line 98, in get_sum_sample_fastq_file_sizes
    latest_fastq_path = sorted(fastq_paths)[-1]
IndexError: list index out of range
```

The error is happening here:

https://github.com/BCCDC-PHL/auto-illumina-run-qc-check/blob/63b1272aa23137b349306552f84198ec08cbec02/auto_illumina_run_qc_check/core.py#L95-L98

...in the case where the glob `<RUN_DIR>/Analysis/*/Data/fastq` doesn't match any directories (there are no fastq dirs for the run).

**Comment by dfornika** [comment]
Fixed in https://github.com/BCCDC-PHL/auto-illumina-run-qc-check/commit/c3e86202133f923ed38f48dfdf1af2a079af8711
