### ISSUE TITLE
Interop summary parsing fails whey `Read 2` not present

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/auto-illumina-run-qc-check#3]
We've seen the tool fail when the key `Read 2` is not present during interop summary parsing:

```
Traceback (most recent call last):
  File "auto-illumina-run-qc-check", line 33, in <module>
    sys.exit(load_entry_point('auto-illumina-run-qc-check', 'console_scripts', 'auto-illumina-run-qc-check')())
  File "auto_illumina_run_qc_check/__main__.py", line 66, in main
    core.qc_check(config, run)
  File "auto_illumina_run_qc_check/core.py", line 127, in qc_check
    qc_metrics = parsers.parse_interop_summary(summary_lines)
  File "auto_illumina_run_qc_check/parsers.py", line 405, in parse_interop_summary
    read_summary = parse_read_summary(summary_lines)
  File "auto_illumina_run_qc_check/parsers.py", line 108, in parse_read_summary
    read_summary_line = parse_read_summary_line(line)
  File "auto_illumina_run_qc_check/parsers.py", line 64, in parse_read_summary_line
    parsed_read_summary_line['ReadNumber'] = level_to_read_number[read_summary_line[idx]]
KeyError: 'Read 2'
```

**Comment by dfornika** [comment]
The error is occuring here:

https://github.com/BCCDC-PHL/auto-illumina-run-qc-check/blob/ea8e0928bfb79314050ed32139bdf62d09f962df/auto_illumina_run_qc_check/parsers.py#L62-L64

...where we're parsing a table that we expect to look something like this:

```
Level,Yield,Projected Yield,Aligned,Error Rate,Intensity C1,%>=Q30,% Occupied
Read 1,75.73,75.73,62.37,0.21,154,92.79,85.66
Read 2 (I),4.54,4.54,0.00,nan,130,95.56,85.66
Read 3 (I),4.54,4.54,0.00,nan,168,92.07,85.66
Read 4,75.72,75.72,61.52,0.37,148,88.81,85.66
Non-indexed,151.45,151.45,61.94,0.29,151,90.80,85.66
Total,160.53,160.53,61.94,0.29,150,90.97,85.66
```

...using a lookup table to translate from the value in the `Level` field to a more straightforward number:

https://github.com/BCCDC-PHL/auto-illumina-run-qc-check/blob/ea8e0928bfb79314050ed32139bdf62d09f962df/auto_illumina_run_qc_check/parsers.py#L34-L42

...but it seems that on at least one run the Indexed (`(I)`) reads are not included in the table:

```
Level,Yield,Projected Yield,Aligned,Error Rate,Intensity C1,%>=Q30,% Occupied
Read 1,20.16,20.16,99.55,0.22,208,92.99,98.79
Read 2,20.16,20.16,98.32,0.36,208,90.38,98.79
Non-indexed,40.32,40.32,98.94,0.29,208,91.68,98.79
Total,40.32,40.32,98.94,0.29,208,91.68,98.79
```

...and we don't include `Read 2` in the lookup table.
